version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm start
    environment:
      - NEWS_API_KEY=88321af79092425696964cb199204f11


